DELETE FROM ORDER_LINE
WHERE order_id IN (
	SELECT order_id 
	FROM ORDERT
	WHERE customer_id = 10001
);

DELETE FROM ORDERT
WHERE customer_id = 10001;

DELETE FROM CUSTOMER
WHERE customer_id = 10001;

SELECT * 
FROM CUSTOMER, ORDERT, ORDER_LINE;
